name: Deploy Docker Image Without Pushing (Local Build + SCP)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        id: tf_apply
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var "region=${{ secrets.AWS_REGION }}" \
            -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var "key_pair_name=${{ secrets.AWS_KEY_PAIR_NAME }}"
          # Extract only the public IP cleanly
          IP=$(terraform output -raw public_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1)
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t nodejs-app .

      - name: Export Docker Image
        run: |
          docker save -o nodejs-app.tar nodejs-app

      - name: Wait for Instance Boot (3 minutes)
        run: sleep 180
        
      - name: Transfer Image to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "nodejs-app.tar"
          target: "~/"

      - name: Load and Run Docker Image on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop node-app || true
            docker rm node-app || true
            docker load -i ~/nodejs-app.tar
            docker run -d -p 3000:3000 \
              -e SECRET_MESSAGE=${{ secrets.APP_SECRET_MESSAGE }} \
              -e USERNAME=${{ secrets.APP_USERNAME }} \
              -e PASSWORD=${{ secrets.APP_PASSWORD }} \
              --name node-app nodejs-app