name: Deploy Docker Image Without Pushing 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        id: tf_apply
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var "region=${{ secrets.AWS_REGION }}" \
            -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var "private_key_path=~/.ssh/id_rsa" \
            -var "key_pair_name=${{ secrets.AWS_KEY_PAIR_NAME }}"
          echo "IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t nodejs-app .

      - name: Export Docker Image
        run: |
          docker save -o nodejs-app.tar nodejs-app

      - name: Transfer Image to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "nodejs-app.tar"
          target: "~/"

      - name: Load and Run Docker Image on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          env:
            SECRET_MESSAGE: ${{ secrets.APP_SECRET_MESSAGE }}
            USERNAME: ${{ secrets.APP_USERNAME }}
            PASSWORD: ${{ secrets.APP_PASSWORD }}
          script: |
            docker stop node-app || true
            docker rm node-app || true
            docker load -i ~/nodejs-app.tar
            docker run -d -p 3000:3000 \
              -e SECRET_MESSAGE=$SECRET_MESSAGE \
              -e USERNAME=$USERNAME \
              -e PASSWORD=$PASSWORD \
              --name node-app nodejs-app